org.gradle.jvmargs=-Xmx4G

# Fabric Properties
minecraft_version=1.21.11
loader_version=0.18.4
fabric_api_version=0.140.2+1.21.11
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.21.11_1.0.9.5
maven_group=nekiplay.meteorplus
archives_base_name=meteor-plus

# Dependencies
starscript_version=0.2.5
orbit_version=0.2.4
xwm_version=1.40.2_Fabric_1.21.11
xmm_version=25.3.2_Fabric_1.21.11
whereisit_version=2.7.3+